name: Docker

on:
  schedule:
    - cron: "0 0 * * 0"
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  build:
    uses: netresearch/.github/.github/workflows/build-container.yml@main
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      image-name: raybeam
      platforms: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
