name: Create GitHub release

on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Release binaries
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: amd64
